// <auto-generated />
namespace Telemedicine.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddDoctorPayment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDoctorPayment));
        
        string IMigrationMetadata.Id
        {
            get { return "201507241506582_AddDoctorPayment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
